"""

    VerifiedDSP
    Copyright (C) {2015}  {Jeremy L Rubin}

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

"""
print "(** DO NOT MODIFY. AUTO GENERATED BY HexGen.py**)"
print "Require Import ZArith."
print "Local Open Scope Z_scope."
g = lambda z: "Definition h%s := %s."%(("0"*(2-len(hex(z)[2:]))) +hex(z)[2:].upper(),z)
for x in xrange(2**8):
    print g(x)
